version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    env_file: .env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Timmick
      - gem_data:/usr/local/bundle  #gemを永久化
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file: .env
    tty: true
    stdin_open: true
volumes:
  mysql-data:
  gem_data:
